{
 "title": "Main",
 "time": { "from": "2023-02-15T20:36:38.361Z", "to": "2023-02-16T20:25:38.819Z" },
 "templating": {
  "list": [
   {
    "name": "group_interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "exhauster_id", "label": "Exhauster", "query": "0, 1, 2, 3, 4, 5" }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Exhausters uptime",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(t.created_at, $group_interval),\n  count(1) as \"count\"\nFROM event t\nWHERE $__timeFilter(t.created_at) and (t.status->'work'->>'is_working')::bool = true\nGROUP BY 1\nORDER BY 1;"
      }
     ]
    },
    {
     "title": "Events count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(t.created_at, $group_interval),\n  count(1) as \"count\",\n  t.exhauster_id as \"exhauster_id\",\n  t.status->'work'->'is_working' as \"is_working\"\nFROM event t\nWHERE $__timeFilter(t.created_at)\nGROUP BY 1, 4, 3\nORDER BY 1;"
      }
     ]
    }
   ]
  },
  { "title": "Exhuster: $exhauster_id", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }, "repeat": "exhauster_id" },
  {
   "title": "Exhauster uptime",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(t.created_at, $group_interval),\n  (case when (t.status -> 'work' ->> 'is_working') :: bool then 1 else 0 end)  as \"working\"\nFROM\n  event t\nWHERE\n  $__timeFilter(t.created_at)\n  and t.exhauster_id = $exhauster_id\nGROUP BY\n  1, 2\nORDER BY\n  1;"
    }
   ]
  },
  {
   "title": "Vibration Bearing 1",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(t.created_at, $group_interval),\n  (t.status->'bearing_1'->'vibration'->'vibration_axial'->>'value') :: numeric as \"vibration_axial\",\n  (t.status->'bearing_1'->'vibration'->'vibration_vertical'->>'value') :: numeric as \"vibration_vertical\",\n  (t.status->'bearing_1'->'vibration'->'vibration_horizontal'->>'value') :: numeric as \"vibration_horizontal\"\nFROM\n  event t\nWHERE\n  $__timeFilter(t.created_at)\n  and t.exhauster_id = $exhauster_id\nGROUP BY\n  1, 2, 3, 4\nORDER BY\n  1;"
    }
   ]
  },
  {
   "title": "Vibration Bearing 2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(t.created_at, $group_interval),\n  (t.status->'bearing_2'->'vibration'->'vibration_axial'->>'value') :: numeric as \"vibration_axial\",\n  (t.status->'bearing_2'->'vibration'->'vibration_vertical'->>'value') :: numeric as \"vibration_vertical\",\n  (t.status->'bearing_2'->'vibration'->'vibration_horizontal'->>'value') :: numeric as \"vibration_horizontal\"\nFROM\n  event t\nWHERE\n  $__timeFilter(t.created_at)\n  and t.exhauster_id = $exhauster_id\nGROUP BY\n  1, 2, 3, 4\nORDER BY\n  1;"
    }
   ]
  },
  {
   "title": "Bearing Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(t.created_at, $group_interval),\n  (t.status->'bearing_1'->'temperature'->>'value') :: numeric as \"bearing_1\",\n  (t.status->'bearing_2'->'temperature'->>'value') :: numeric as \"bearing_2\",\n  (t.status->'bearing_3'->'temperature'->>'value') :: numeric as \"bearing_3\",\n  (t.status->'bearing_4'->'temperature'->>'value') :: numeric as \"bearing_4\",\n  (t.status->'bearing_5'->'temperature'->>'value') :: numeric as \"bearing_5\",\n  (t.status->'bearing_6'->'temperature'->>'value') :: numeric as \"bearing_6\",\n  (t.status->'bearing_7'->'temperature'->>'value') :: numeric as \"bearing_7\",\n  (t.status->'bearing_8'->'temperature'->>'value') :: numeric as \"bearing_8\",\n  (t.status->'bearing_9'->'temperature'->>'value') :: numeric as \"bearing_9\"\nFROM\n  event t\nWHERE\n  $__timeFilter(t.created_at)\n  and t.exhauster_id = $exhauster_id\nGROUP BY\n  1, 2, 3, 4, 5, 6, 7, 8, 9, 10\nORDER BY\n  1;"
    }
   ]
  },
  {
   "title": "Vibration Bearing 7",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(t.created_at, $group_interval),\n  (t.status->'bearing_7'->'vibration'->'vibration_axial'->>'value') :: numeric as \"vibration_axial\",\n  (t.status->'bearing_7'->'vibration'->'vibration_vertical'->>'value') :: numeric as \"vibration_vertical\",\n  (t.status->'bearing_7'->'vibration'->'vibration_horizontal'->>'value') :: numeric as \"vibration_horizontal\"\nFROM\n  event t\nWHERE\n  $__timeFilter(t.created_at)\n  and t.exhauster_id = $exhauster_id\nGROUP BY\n  1, 2, 3, 4\nORDER BY\n  1;"
    }
   ]
  },
  {
   "title": "Vibration Bearing 8",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(t.created_at, $group_interval),\n  (t.status->'bearing_8'->'vibration'->'vibration_axial'->>'value') :: numeric as \"vibration_axial\",\n  (t.status->'bearing_8'->'vibration'->'vibration_vertical'->>'value') :: numeric as \"vibration_vertical\",\n  (t.status->'bearing_8'->'vibration'->'vibration_horizontal'->>'value') :: numeric as \"vibration_horizontal\"\nFROM\n  event t\nWHERE\n  $__timeFilter(t.created_at)\n  and t.exhauster_id = $exhauster_id\nGROUP BY\n  1, 2, 3, 4\nORDER BY\n  1;"
    }
   ]
  },
  {
   "title": "Cooler",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(t.created_at, $group_interval),\n  (t.status->'cooler_water'->>'temperature_after') :: numeric as \"cooler_water_temperature_after\",\n  (t.status->'cooler_water'->>'temperature_before') :: numeric as \"cooler_water_temperature_before\",\n  (t.status->'cooler_oil'->>'temperature_after') :: numeric as \"cooler_oil_temperature_after\",\n  (t.status->'cooler_oil'->>'temperature_before') :: numeric as \"cooler_oil_temperature_before\"\nFROM\n  event t\nWHERE\n  $__timeFilter(t.created_at)\n  and t.exhauster_id = $exhauster_id\nGROUP BY\n  1, 2, 3, 4, 5\nORDER BY\n  1;"
    }
   ]
  },
  {
   "title": "Gas Collector",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(t.created_at, $group_interval),\n  (t.status->'gas_collector'->>'temperature_before') :: numeric as \"temperature_before\",\n  (t.status->'gas_collector'->>'underpressure_before') :: numeric as \"underpressure_before\"\nFROM\n  event t\nWHERE\n  $__timeFilter(t.created_at)\n  and t.exhauster_id = $exhauster_id\nGROUP BY\n  1, 2, 3\nORDER BY\n  1;"
    }
   ]
  },
  {
   "title": "Drive Voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(t.created_at, $group_interval),\n  (t.status->'drive'->>'rotor_voltage') :: numeric as \"rotor_voltage\",\n  (t.status->'drive'->>'stator_voltage') :: numeric as \"stator_voltage\"\nFROM\n  event t\nWHERE\n  $__timeFilter(t.created_at)\n  and t.exhauster_id = $exhauster_id\nGROUP BY\n  1, 2, 3\nORDER BY\n  1;"
    }
   ]
  },
  {
   "title": "Drive Voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(t.created_at, $group_interval),\n  (t.status->'drive'->>'rotor_current') :: numeric as \"rotor_current\",\n  (t.status->'drive'->>'stator_current') :: numeric as \"stator_current\"\nFROM\n  event t\nWHERE\n  $__timeFilter(t.created_at)\n  and t.exhauster_id = $exhauster_id\nGROUP BY\n  1, 2, 3\nORDER BY\n  1;"
    }
   ]
  },
  {
   "title": "Oil",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(t.created_at, $group_interval),\n  (t.status->'oil'->>'oil_level') :: numeric as \"oil_level\",\n  (t.status->'drive'->>'oil_pressure') :: numeric as \"oil_pressure\"\nFROM\n  event t\nWHERE\n  $__timeFilter(t.created_at)\n  and t.exhauster_id = $exhauster_id\nGROUP BY\n  1, 2, 3\nORDER BY\n  1;"
    }
   ]
  },
  {
   "title": "Gate Valve Position",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(t.created_at, $group_interval),\n  (t.status->'gate_valve'->>'gas_valve_position') :: numeric as \"gas_valve_position\"\nFROM\n  event t\nWHERE\n  $__timeFilter(t.created_at)\n  and t.exhauster_id = $exhauster_id\nGROUP BY\n  1, 2\nORDER BY\n  1;"
    }
   ]
  }
 ]
}